apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - manifests/deployment.yaml
 - manifests/svc.yaml
 - manifests/route.yaml
 - secrets/
 - manifests/network-policy.yaml
 - manifests/network-policy-denyall.yaml



