apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: isolate-secret-store
spec:
  podSelector:
    matchLabels:
      app: secrets-store
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              accessSecretStore: "true"
        - podSelector:
            matchLabels:
              app: secrets-store-consumer
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
#      ports:
#        - protocol: TCP
#          port: 8080
