apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:

  - name: encrypt-token-secret
    envs:
      - token.env
    type: Opaque
  - name: secret-data
    options:
      disableNameSuffixHash: true
    files:
      - confidential
      - password
      - token
      - secret
    type: Opaque