apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keep-secrets-encrypted-app
  name: keep-secrets-encrypted-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keep-secrets-encrypted-app
  strategy: {}
  template:
    metadata:
      labels:
        app: keep-secrets-encrypted-app
    spec:
      containers:
        - name: container-1
          image: busybox
          envFrom:
            - secretRef:
                name: secret_name
          command: [ "/bin/sh" ]
          args: [ "-c", "sleep infinity" ]
